# Generated by Django 4.2.4 on 2023-08-22 23:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourierTransactionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourierWeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday_date', models.DateField(db_index=True)),
                ('income', models.FloatField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes_handler_app.courier')),
            ],
        ),
        migrations.CreateModel(
            name='CourierTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_date_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('income', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes_handler_app.courier')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes_handler_app.customertype')),
            ],
        ),
        migrations.CreateModel(
            name='CourierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('explanation', models.CharField(default='', max_length=500)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes_handler_app.courier')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes_handler_app.couriertransactionreason')),
            ],
        ),
        migrations.CreateModel(
            name='CourierDailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('income', models.FloatField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incomes_handler_app.courier')),
            ],
        ),
    ]
